### ISSUE TITLE
Node Connectivity in Web Interface

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#12]
Nodes are not sucesfully connected if the user double clicks on one of them.

**Comment by adreaskar** [comment]
Άλλαξα λίγο την λογική στο double click on same dot, για να είναι λίγο πιο userfriendly.

Επίσης πρόσθεσα αρκετούς νέους κανόνες για ποιές συνδέσεις επιτρέπονται και ποιές όχι.

Τώρα για οτιδήποτε άλλο, πιστεύω χρειάζεται testing και από κάποιον άλλο γιατί εγώ είμαι αρκετά biased επειδή ξέρω πως δουλέυει και δεν μπορώ να δοκιμάσω όλα τα τυχαία σενάρια που θα τύχαιναν σε έναν καινούριο χρήστη.

Για αυτό το μετακινώ σε In Review
