### ISSUE TITLE
Graph Save/Download

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#13]
Sometimes graphs in function modelling or process modelling are not eligible for saving/downloading. Further investigation is needed to identify the source of the problem.

**Comment by adreaskar** [comment]
Δεν μπορώ να κάνω recreate το issue.

Όσο μεγάλος και αν είναι ο γράφος καταφέρνω να τον κάνω save (είχα σημειώσει σαν hint το μέγεθος του γράφου).

Θα συνεχίσω την έρευνα μήπως προκαλούσε κάτι άλλο το πρόβλημα, meanwhile @yannispoulakis αν θυμάσαι κάποιο άλλο χαρακτηριστικο όταν σου έτυχε please comment below and tag me.
