### ISSUE TITLE
Dataset Preview

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#14]
Preview of the available datasets should exist to allow the user to identify format, colnames, etc.

**Comment by adreaskar** [comment]
Μια καλή ιδέα για αυτό είναι να δημιουργηθεί ένα νέο interface **Collected Data**, ίδιο με το **Data Ingestion** το οποίο να έχει όλα τα collected sets με τις ιδιότητες τους, και διπλα ένα παρόμοιο πεδίο για dataset preview.

Το Ingestion interface γίνεται όλο πιο απαιτητικό όσον αφορά το Http Request κομμάτι οπότε το collected datasets κομμάτι γίνεται όλο και πιο άβολο στην χρήση του όπως είναι τώρα διαμορφωμένο.

Όλα αυτά βέβαια για επόμενο Iteration, απλά αφήνω το σχόλιο εδώ σαν ιδέα όταν κάνουμε revisit το issue.
