### ISSUE TITLE
Data Normalization - Dataset Separator

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#19]
The user should be able to define the separator of the dataset. For example a csv file is commonly separated by the comma character. However other file types or neutral file types (.dat, .txt) would require the dataset separator to be explicitly defined.

**Comment by adreaskar** [comment]
Η φόρμα για το Http Request έχει υποχρεωτικό πεδίο για την δήλωση του separator character, το οποίο περιλαμβάνεται στο JSON που συνεχίζει στα υπόλοιπα services.

Moving to Ready

**Comment by karamolegkos** [comment]
To Orchestration είναι έτοιμο όπως έχω αναφερθεί και στο δικό του σχετικό issue.
