### ISSUE TITLE
Visualization Interface

### ISSUE THREAD

**Issue by adreaskar** [DIASTEMA-UPRC/web-application#31]
Πρέπει να φτιαχτεί η διεπαφή που θα φιλοξενεί τις ολοκληρωμένες αναλύσεις του χρήστη, για τις οποίες μπορεί να δημιουργήσει οπτικοποιήσεις.

Tasks:
- [x] Δημιουργία διεπαφής
- [x] Προβολή ολοκληρωμένων αναλύσεων
- [x] Προβολή μεταδεδομένων για κάθε ανάλυση
- [x] Για κάθε ανάλυση θα υπάρχει διαθέσιμη επιλογή οπτικοποίησης αποτελεσμάτων
    - [x] Με το πάτημα αυτής θα εμφανίζονται τα γραφήματα analysis results
- [x] Για κάθε ανάλυση θα υπάρχει διαθέσιμη επιλογή οπτικοποίησης μετρήσεων εκτέλεσης

Linked Issues: #28 #29

**Comment by adreaskar** [comment]
Όλα τα tasks για αυτό το issue έχουν ολοκληρωθεί. 
Αναμένω το call στις 13/01 με @konvoulgaris και @karamolegkos για να δώ αν θα χρειαστεί κάποια αλλαγή.

**Comment by adreaskar** [comment]
Δεν χρειάζονται αλλαγές, moving to Integration

**Comment by karamolegkos** [comment]
@adreaskar check slack
