### ISSUE TITLE
Analytics Results Interface

### ISSUE THREAD

**Issue by adreaskar** [DIASTEMA-UPRC/web-application#32]
Πρέπει να δημιουργηθεί μια διεπαφή η οποία θα προβάλει τις οπτικοποίησεις των αποτελεσμάτωντης ανάλυσης.

Tasks:
- [x] Πρέπει να παίρνει input απο το MinIO object storage του server
- [x] Να προβάλει τις οπτικοποιήσεις που ζητήθηκαν για κάθε ανάλυση
- [x]  Φίλτρα για επιλογή οπτικοποιήσεων

Update:
- [ ] Να μπορούν να κλείνουν τα available pipelines για να εχει περισσοτερο χωρο το visualization tab
- [ ] Να μπορεί να κάνει export το report σε PDF

Linked Issues: #28 #29 #30 #31 DIASTEMA-UPRC/monitoring#6

**Comment by karamolegkos** [comment]
Μετά από Integration Testing γνωρίζουμε πως το flow λειτουργεί σωστά. Όμως πρέπει να γίνει end to end με non dummy αποτελέσματα για να γνωρίζουμε πως εμφανίζονται τα αποτελέσματα σωστά από MinIO (λόγο connectivity).

**Comment by adreaskar** [comment]
Το export functionality είναι περιορισμένο καθώς τα γραφήματα έρχονται απο external source

**Comment by adreaskar** [comment]
Update: 
- [ ] Να μπορούν να κλείνουν τα available pipelines για να εχει περισσοτερο χωρο το visualization tab
