### ISSUE TITLE
Add Visualization Node

### ISSUE THREAD

**Issue by adreaskar** [DIASTEMA-UPRC/web-application#33]
Πρέπει να επιστρέψει το visualization node στο Process Modeling

Tasks:
- [x] Προσθήκη Visualization node
- [x] Πρέπει να έχει πεδίο για να ονομάζει ο χρήστης το κάθε visualization
- [x] Ενημέρωση του τελικού γράφου

**Comment by karamolegkos** [comment]
Δουλεύει καλώς μετά από Integration Testing.
