### ISSUE TITLE
Performance Results Interface

### ISSUE THREAD

**Issue by adreaskar** [DIASTEMA-UPRC/web-application#37]
Πρέπει να δημιουργηθεί μια διεπαφή η οποία θα προβάλει τα αποτελέσματα απο τις επιδόσεις της κάθε ανάλυσης.

Update:
- [x] Προσθηκη συνολικου execution-speed στα τελικα αποτελεσματα

**Comment by karamolegkos** [comment]
@adreaskar check slack.

**Comment by karamolegkos** [comment]
Show agregated results for the performance of an analysis.

**Comment by adreaskar** [comment]
Στο πεδιο "performance" στο UIDB θα προστεθεί:
```
{
    “analysis” : “execution-speed” : int (milliseconds)
}
```

**Comment by adreaskar** [comment]
Εχει γινει η ενημερωση για το analysis execution speed
