### ISSUE TITLE
API request UI

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#6]
Δημιουργία ui στο οποίο δηλώνονται τα απαραίτητα στοιχεία για την κλήση οποιουδήποτε API. 

Ένα API request αποτελείται από τα στοιχεία : 
- Τύπος Request (POST, GET, PUT etc.) 
- Headers 
- Body 
- Parameters 

Για τα παραπάνω θα πρέπει να υπάρχουν τα απαραίτητα πεδία. ακόμη θα πρέπει να φαίνεται στον χρήστη το τι επιστρέφει το call  στο κληθέν API. Αυτό πρέπει να γίνεται πριν την ολοκλήρωση του γράφου και κατά την διεπαφή του χρήστη με το γενικότερο UI, μιας και το task συμπεριλαμβάνεται στην εισαγωγή δεδομένων. Μπορεί δηλαδή ο χρήστης να θέλει να δεί τι εξάγει το πρώτο call προκειμένου να πραγματοποιήσει το 2ο.

**Comment by adreaskar** [comment]
Progress:

TODO:
- [X] Δημιουργία διεπαφής για HTTP requests.
- [X] Πεδίο για εισαγωγή χαρακτηριστικών του request.
  - [X] Method (GET, POST, PUT, DELETE)
  - [X] Parameters
  - [X] Headers
  - [X] Body 
- [X] Πεδίο για την εμφάνιση της απάντησης του request
  - [X] Δοκιμαστική κλήση του request για την εμφάνιση της απάντησης

**Comment by adreaskar** [comment]
Το interface για  το data ingestion / HTTP request έχει ολοκληρωθεί και περιέχει όλα όσα αναγράφονται στο παραπάνω σχόλιο

**Comment by karamolegkos** [comment]
This service is working and it is tested in the integration phase ✔️.
After the next Internal Meeting, I propose we move it as Done @yannispoulakis .
