### ISSUE TITLE
Function Modelling UI

### ISSUE THREAD

**Issue by yannispoulakis** [DIASTEMA-UPRC/web-application#8]

**Comment by yannispoulakis** [comment]
Δημιουργία UI όπως συζητήθηκε στο τελευταίο call για την δήλωση μαθηματικών πράξεων και συνθηκών.

**Comment by adreaskar** [comment]
Έχει ξεκινήσει ο σχεδιασμός της διεπαφής του Function Modelling με τα εξής tasks που πρέπει να γίνουν:
- [X] Σχεδιασμός του tools sidebar, το οποίο πρέπει να περιέχει όλες τις διαθέσιμες συναρτήσεις που προσφέρει το DIASTEMA
- [ ] Επαναπροσδιορισμός της λογικής για την δημιουργία των nodes, καθώς η λογική του Process Modelling δεν μπορεί να κάνει scale για να καλύψει το μέγεθος του Function Modelling.
- [ ] Δημιουργία λογικής για τους κανόνες σύνδεσης των κόμβων μεταξύ τους.
- [ ] Εξαγωγή του γράφου με το νέο σχήμα που έχει πλεον οριστεί στο PDF, διατηρώντας παράλληλα την λογική του παλιού.

**Comment by adreaskar** [comment]
Ο αλγόριθμος για την λογική του Function Modelling ολοκληρώθηκε, η διαδικασία είναι πλέον αυτοματοποιημένη και μπορεί να υποστηρίξει το scale του Function Modelling. 

Ας κορροιδεψουμε όλοι μαζι τον πρόχειρο αλγόριθμο του Process Modelling.

**Comment by adreaskar** [comment]
Progress: 
- [X] Δημιουργήθηκε το schema για τα `Simple Functions` και μπορούν να εξαχθούν κανονικά.
- [X] Δημιουργήθηκε η λογική με την οποία η εφαρμογή αποφασίζει το `output` του Simple Function (όσο εκτενές και αν είναι), κάνωντας προσπέλαση στον γράφο και υπολογίζοντας όλες τις υπο-περιπτώσεις πράξεων.

Next steps:
- [ ] Αποθήκευση ενός simple function ώστε να εμφανίζεται στην διεπαφή σαν complex function και να μπορεί να χρησιμοποιηθεί μέσα σε μια συνάρτηση.
- [ ] Ενημέρωση του graph schema για να υποστηρίζει και τα complex functions
- [ ] Λογική για κανόνες ένωσης των κόμβων, όπως αναφέρεται στο OP.

**Comment by adreaskar** [comment]
Progress:
Δημιουργήθηκε η λογική για την σύνδεση των κόμβων βάσει του output της κάθε συνάρτησης, και του input της συνάρτησης στην οποία πάει να συνδεθεί.

**Comment by adreaskar** [comment]
Progress:

Δημιουργήθηκε η λογική για την αποθήκευση των Simple Functions, οι οποίες εμφανίζονται τόσο στην διεπαφή των Functions, όσο και σαν διαθέσιμες συναρτήσεις στο Function Modelling.

Next steps:

Προχωράω στην λειτουργικότητα των Custom Functions και του graph schema τους.

**Comment by adreaskar** [comment]
Progress:

Έκανα λίγο step back να φτιαξω κάποια μικρά αλλά σημαντικά bugs που παρατήρησα ότι υπάρχουν:
- [X] Πλέον γίνεται σωστός έλεγχος για διακλάδωση κόμβων και εμφανίζεται ανάλογο μήνυμα.
- [X] Τα Feature Based functions να μην δέχονται απλες μεταβλητές αλλά μεταβλητές column (π.χ. το Amount Of function δέχεται Int Column variable σαν input και όχι απλό Int).
- [X] Διόρθωση του αλγορίθμου που υπολογίζει τα from / next για κάθε κόμβο. Πλέον είναι πιο αποδοτικός και υπολογίζει πάντα σωστά τα next και from.

Επίσης:
- [X] Πλέον ο χρήστης μπορεί να εμφανίσει σαν node ένα αποθηκευμένο function, το οποίο του δείχνει τι παίρνει σαν έισοδο και τι βγάζει σαν έξοδο.

Next steps:

- [ ] Έλεγχος ότι τα nodes των αποθηκευμένων functions παίρνουν σωστό input.
- [ ] Ενημέρωση του graph schema να περιλαμβάνει τα Complex Functions όπως αναφέρεται στο PDF

**Comment by adreaskar** [comment]
Ολοκληρώθηκαν όλα τα tasks του Function Modelling. Marking as done

**Comment by karamolegkos** [comment]
This service is working and it is tested in the integration phase ✔️.
After the next Internal Meeting, I propose we move it as Done @yannispoulakis .
