### ISSUE TITLE
Update Process Modelling

### ISSUE THREAD

**Issue by adreaskar** [DIASTEMA-UPRC/web-application#9]
Πρέπει να γίνει ενημέρωση του Process Modelling ώστε να περιέχει τα εξής:

- [X] `Saved Functions:` Οι συναρτήσεις που έχει φτιάξει ο χρήστης απο το `Function Modelling`.
- [x] `Dataset Node:` Δείχνει όλα τα διαθέσιμα datasets με τα ανάλογα features τους για να χρησιμοποιηθούν στο pipeline.
- [x] ~~`Ενημερωτικά μηνύματα:` User friendly μηνύματα που τον ενημερώνουν για τον τύπο μεταβλητών που περιέχει ένα dataset column.~~

Επίσης πρέπει να γίνουν οι εξής διορθώσεις:

- [X] Ενημέρωση UI για καλύτερη εμπειρία χρήσης.
- [x] Προσαρμογή της λογικής για την δημιουργία των κόμβων, βάσει της βελτιωμένης λογικής του Function Modelling.
- [x] Προσαρμογή της λογικής παραγωγής των **from / next**, βάσει της βελτιωμένης λογικής του Function Modelling.
- [x] Προσαρμογή της λογικής παραγωγής του τελικού JSON βάσει της βελτιωμένης λογικής του Function Modelling.

**Comment by adreaskar** [comment]
Progress:

Η δημιουργία των κόμβων προσαρμόστηκε βάσει της βελτιωμένης λογικής του Function Modelling.

**Comment by adreaskar** [comment]
Όλα τα tasks ολοκληρώθηκαν, moving to Ready

**Comment by karamolegkos** [comment]
This service is working and it is tested in the integration phase ✔️.
After the next Internal Meeting, I propose we move it as Done @yannispoulakis .
